version: "3.8"

services:
    postgres:
        image: postgres
        restart: always
        ports:
            - "5432:5432"
        environment:
            - DATABASE_HOST=127.0.0.1
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=1234
            - POSTGRES_DB=facturaciondb
        volumes:
            - postgres_vol_factu:/var/lib/postgresql/data

volumes:
    postgres_vol_factu:
        driver: local
